baseurl: /swift-macos

collections:
  getting_started:
    output: true
    permalink: /:name
  swift:
    output: true
    permalink: /:name
  swiftui:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: "getting_started"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "swift"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "swiftui"
    values:
      layout: "page"

exclude: [README.md, Gemfile]